parser: babel-eslint
env:
  browser: true
  node: true
  jest/globals: true
  es6: true

plugins:
  - jest
  - prettier
  - react
  - react-hooks

extends:
  - eslint:recommended
  - plugin:jest/recommended
  - plugin:react/recommended
  - prettier

parserOptions:
  ecmaVersion: 8
  sourceType: module
  ecmaFeatures:
    classes: true
    jsx: true

rules:
  prefer-arrow-callback: 2
  prefer-const: 2
  prefer-promise-reject-errors: 2
  prettier/prettier: 2
  strict: [2, global]
  semi: [2, never]
  react-hooks/rules-of-hooks: 2
  react-hooks/exhaustive-deps: 1

settings:
  react:
    pragma: React
    version: detect